// <auto-generated />
using System;
using Ergon.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ergon.API.Migrations
{
    [DbContext(typeof(ErgonContext))]
    [Migration("20260616131843_SeedDataPublicHoliday")]
    partial class SeedDataPublicHoliday
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ergon.Models.Attendance", b =>
                {
                    b.Property<Guid>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AttendanceStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly>("ClockInTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("ClockOutTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("LateEntry")
                        .HasColumnType("boolean");

                    b.Property<bool>("LateExit")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("AttendanceId")
                        .HasName("pk_attendance");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("Ergon.Models.BankAccount", b =>
                {
                    b.Property<Guid>("BankAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountHolderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("IfscCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("BankAccountId")
                        .HasName("pk_bankaccount");

                    b.HasIndex("EmployeeId");

                    b.ToTable("BankAccounts");
                });

            modelBuilder.Entity("Ergon.Models.Branch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BranchId"));

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BranchId")
                        .HasName("pk_branch");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            BranchId = 1,
                            BranchName = "Bangalore"
                        },
                        new
                        {
                            BranchId = 2,
                            BranchName = "Chennai"
                        },
                        new
                        {
                            BranchId = 3,
                            BranchName = "Mumbai"
                        });
                });

            modelBuilder.Entity("Ergon.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CityId"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CityId")
                        .HasName("pk_city");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            CityName = "Bangalore"
                        },
                        new
                        {
                            CityId = 2,
                            CityName = "Chennai"
                        },
                        new
                        {
                            CityId = 3,
                            CityName = "Mumbai"
                        });
                });

            modelBuilder.Entity("Ergon.Models.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CountryId"));

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CountryId")
                        .HasName("pk_country");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            CountryName = "India"
                        });
                });

            modelBuilder.Entity("Ergon.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DepartmentId")
                        .HasName("pk_department");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            DepartmentName = "Engineering"
                        },
                        new
                        {
                            DepartmentId = 2,
                            DepartmentName = "Human Resources"
                        },
                        new
                        {
                            DepartmentId = 3,
                            DepartmentName = "Finance"
                        },
                        new
                        {
                            DepartmentId = 4,
                            DepartmentName = "Sales"
                        },
                        new
                        {
                            DepartmentId = 5,
                            DepartmentName = "Operations"
                        });
                });

            modelBuilder.Entity("Ergon.Models.Designation", b =>
                {
                    b.Property<int>("DesignationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DesignationId"));

                    b.Property<string>("DesignationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DesignationId")
                        .HasName("pk_designation");

                    b.ToTable("Designations");

                    b.HasData(
                        new
                        {
                            DesignationId = 1,
                            DesignationName = "Software Engineer"
                        },
                        new
                        {
                            DesignationId = 2,
                            DesignationName = "Senior Software Engineer"
                        },
                        new
                        {
                            DesignationId = 3,
                            DesignationName = "HR Executive"
                        },
                        new
                        {
                            DesignationId = 4,
                            DesignationName = "HR Manager"
                        },
                        new
                        {
                            DesignationId = 5,
                            DesignationName = "Finance Executive"
                        },
                        new
                        {
                            DesignationId = 6,
                            DesignationName = "Sales Executive"
                        },
                        new
                        {
                            DesignationId = 7,
                            DesignationName = "Operations Manager"
                        });
                });

            modelBuilder.Entity("Ergon.Models.Employee", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("text");

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateOfJoining")
                        .HasColumnType("date");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<int>("DesignationId")
                        .HasColumnType("integer");

                    b.Property<string>("EmploymentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LeaveEntitlementId")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PersonalEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pfp")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ReportsTo")
                        .HasColumnType("uuid");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("SalaryStructureId")
                        .HasColumnType("integer");

                    b.Property<int>("ShiftId")
                        .HasColumnType("integer");

                    b.Property<int>("StateId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("WorkEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EmployeeId")
                        .HasName("pk_employee");

                    b.HasIndex("BranchId");

                    b.HasIndex("CityId");

                    b.HasIndex("CountryId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DesignationId");

                    b.HasIndex("LeaveEntitlementId");

                    b.HasIndex("ReportsTo");

                    b.HasIndex("RoleId");

                    b.HasIndex("SalaryStructureId");

                    b.HasIndex("ShiftId");

                    b.HasIndex("StateId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Ergon.Models.EmployeeDocument", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("DocumentId")
                        .HasName("pk_employeedocument");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeDocuments");
                });

            modelBuilder.Entity("Ergon.Models.Leave", b =>
                {
                    b.Property<Guid>("LeaveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActionedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("FromDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsHalfDay")
                        .HasColumnType("boolean");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("ToDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("LeaveId")
                        .HasName("pk_leave");

                    b.HasIndex("ActionedBy");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LeaveTypeId");

                    b.ToTable("Leaves");
                });

            modelBuilder.Entity("Ergon.Models.LeaveEntitlement", b =>
                {
                    b.Property<int>("LeaveEntitlementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LeaveEntitlementId"));

                    b.Property<string>("LeaveEntitlementName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LeaveEntitlementId")
                        .HasName("pk_leaveentitlement");

                    b.ToTable("LeaveEntitlements");

                    b.HasData(
                        new
                        {
                            LeaveEntitlementId = 1,
                            LeaveEntitlementName = "Standard Entitlement"
                        });
                });

            modelBuilder.Entity("Ergon.Models.LeaveEntitlementComponent", b =>
                {
                    b.Property<int>("LeaveEntitlementComponentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LeaveEntitlementComponentId"));

                    b.Property<int>("LeaveEntitlementId")
                        .HasColumnType("integer");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalDays")
                        .HasColumnType("integer");

                    b.HasKey("LeaveEntitlementComponentId")
                        .HasName("pk_leaveentitlementcomponent");

                    b.HasIndex("LeaveEntitlementId");

                    b.HasIndex("LeaveTypeId");

                    b.ToTable("LeaveEntitlementComponents");

                    b.HasData(
                        new
                        {
                            LeaveEntitlementComponentId = 1,
                            LeaveEntitlementId = 1,
                            LeaveTypeId = 1,
                            TotalDays = 12
                        },
                        new
                        {
                            LeaveEntitlementComponentId = 2,
                            LeaveEntitlementId = 1,
                            LeaveTypeId = 2,
                            TotalDays = 6
                        },
                        new
                        {
                            LeaveEntitlementComponentId = 3,
                            LeaveEntitlementId = 1,
                            LeaveTypeId = 3,
                            TotalDays = 15
                        },
                        new
                        {
                            LeaveEntitlementComponentId = 4,
                            LeaveEntitlementId = 1,
                            LeaveTypeId = 4,
                            TotalDays = 0
                        },
                        new
                        {
                            LeaveEntitlementComponentId = 5,
                            LeaveEntitlementId = 1,
                            LeaveTypeId = 5,
                            TotalDays = 0
                        });
                });

            modelBuilder.Entity("Ergon.Models.LeaveType", b =>
                {
                    b.Property<int>("LeaveTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LeaveTypeId"));

                    b.Property<string>("LeaveTypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LeaveTypeId")
                        .HasName("pk_leavetype");

                    b.ToTable("LeaveTypes");

                    b.HasData(
                        new
                        {
                            LeaveTypeId = 1,
                            LeaveTypeName = "Casual Leave"
                        },
                        new
                        {
                            LeaveTypeId = 2,
                            LeaveTypeName = "Sick Leave"
                        },
                        new
                        {
                            LeaveTypeId = 3,
                            LeaveTypeName = "Privilege Leave"
                        },
                        new
                        {
                            LeaveTypeId = 4,
                            LeaveTypeName = "Leave Without Pay"
                        },
                        new
                        {
                            LeaveTypeId = 5,
                            LeaveTypeName = "Compensatory Off"
                        });
                });

            modelBuilder.Entity("Ergon.Models.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("NotificationId")
                        .HasName("pk_notification");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Ergon.Models.Payroll", b =>
                {
                    b.Property<Guid>("PayrollId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<decimal>("NetSalary")
                        .HasColumnType("numeric");

                    b.Property<string>("PayrollStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("PayrollId")
                        .HasName("pk_payroll");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Payrolls");
                });

            modelBuilder.Entity("Ergon.Models.PayrollComponent", b =>
                {
                    b.Property<Guid>("PayrollComponentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PayrollComponentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayrollComponentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PayrollId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("PayrollComponentId")
                        .HasName("pk_payrollcomponent");

                    b.HasIndex("PayrollId");

                    b.ToTable("PayrollComponents");
                });

            modelBuilder.Entity("Ergon.Models.PublicHoliday", b =>
                {
                    b.Property<int>("PublicHolidayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PublicHolidayId"));

                    b.Property<DateOnly>("PublicHolidayDate")
                        .HasColumnType("date");

                    b.Property<string>("PublicHolidayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PublicHolidayId")
                        .HasName("pk_publicholiday");

                    b.ToTable("PublicHolidays");

                    b.HasData(
                        new
                        {
                            PublicHolidayId = 1,
                            PublicHolidayDate = new DateOnly(2026, 1, 1),
                            PublicHolidayName = "New Year's Day"
                        },
                        new
                        {
                            PublicHolidayId = 2,
                            PublicHolidayDate = new DateOnly(2026, 1, 26),
                            PublicHolidayName = "Republic Day"
                        },
                        new
                        {
                            PublicHolidayId = 3,
                            PublicHolidayDate = new DateOnly(2026, 8, 15),
                            PublicHolidayName = "Independence Day"
                        },
                        new
                        {
                            PublicHolidayId = 5,
                            PublicHolidayDate = new DateOnly(2026, 12, 25),
                            PublicHolidayName = "Christmas Day"
                        });
                });

            modelBuilder.Entity("Ergon.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Expiry")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RefreshTokenId")
                        .HasName("pk_refreshtoken");

                    b.HasIndex("EmployeeId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Ergon.Models.ReviewCycle", b =>
                {
                    b.Property<Guid>("ReviewCycleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("ReviewCycleStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReviewName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ReviewCycleId")
                        .HasName("pk_reviewcycle");

                    b.ToTable("ReviewCycles");
                });

            modelBuilder.Entity("Ergon.Models.ReviewCycleDetails", b =>
                {
                    b.Property<Guid>("ReviewCycleDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("FeedbackScore")
                        .HasColumnType("numeric");

                    b.Property<string>("ManagerComments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ReviewCycleId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("SelfScore")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ReviewCycleDetailsId")
                        .HasName("pk_reviewcycledetails");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ReviewCycleId");

                    b.ToTable("ReviewCycleDetails");
                });

            modelBuilder.Entity("Ergon.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RoleId")
                        .HasName("pk_role");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "HR Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "HR"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "Manager"
                        },
                        new
                        {
                            RoleId = 4,
                            RoleName = "Employee"
                        });
                });

            modelBuilder.Entity("Ergon.Models.SalaryComponent", b =>
                {
                    b.Property<int>("SalaryComponentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SalaryComponentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("ComponentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ComponentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("SalaryStructureId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("SalaryComponentId")
                        .HasName("pk_salarycomponent");

                    b.HasIndex("SalaryStructureId");

                    b.ToTable("SalaryComponents");
                });

            modelBuilder.Entity("Ergon.Models.SalaryStructure", b =>
                {
                    b.Property<int>("SalaryStructureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SalaryStructureId"));

                    b.Property<string>("SalaryStructureName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SalaryStructureId")
                        .HasName("pk_salarystructure");

                    b.ToTable("SalaryStructures");

                    b.HasData(
                        new
                        {
                            SalaryStructureId = 1,
                            SalaryStructureName = "Structure A"
                        },
                        new
                        {
                            SalaryStructureId = 2,
                            SalaryStructureName = "Structure B"
                        },
                        new
                        {
                            SalaryStructureId = 3,
                            SalaryStructureName = "Structure C"
                        });
                });

            modelBuilder.Entity("Ergon.Models.Shift", b =>
                {
                    b.Property<int>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ShiftId"));

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("ShiftName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("ShiftId")
                        .HasName("pk_shift");

                    b.ToTable("Shifts");

                    b.HasData(
                        new
                        {
                            ShiftId = 1,
                            EndTime = new TimeOnly(18, 0, 0),
                            ShiftName = "Morning",
                            StartTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            ShiftId = 2,
                            EndTime = new TimeOnly(23, 0, 0),
                            ShiftName = "Evening",
                            StartTime = new TimeOnly(14, 0, 0)
                        });
                });

            modelBuilder.Entity("Ergon.Models.State", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StateId"));

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StateId")
                        .HasName("pk_state");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            StateId = 1,
                            StateName = "Karnataka"
                        },
                        new
                        {
                            StateId = 2,
                            StateName = "Tamil Nadu"
                        },
                        new
                        {
                            StateId = 3,
                            StateName = "Maharashtra"
                        });
                });

            modelBuilder.Entity("Ergon.Models.TaxSlab", b =>
                {
                    b.Property<int>("TaxSlabId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TaxSlabId"));

                    b.Property<decimal>("MaxIncome")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MinIncome")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TaxPercentage")
                        .HasColumnType("numeric");

                    b.HasKey("TaxSlabId")
                        .HasName("pk_taxslab");

                    b.ToTable("TaxSlabs");
                });

            modelBuilder.Entity("Ergon.Models.Attendance", b =>
                {
                    b.HasOne("Ergon.Models.Employee", "Employee")
                        .WithMany("Attendances")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_employee");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Ergon.Models.BankAccount", b =>
                {
                    b.HasOne("Ergon.Models.Employee", "Employee")
                        .WithMany("BankAccounts")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bankaccount_employee");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Ergon.Models.Employee", b =>
                {
                    b.HasOne("Ergon.Models.Branch", "Branch")
                        .WithMany("Employees")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_employee_branch");

                    b.HasOne("Ergon.Models.City", "City")
                        .WithMany("Employees")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ergon.Models.Country", "Country")
                        .WithMany("Employees")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ergon.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_employee_department");

                    b.HasOne("Ergon.Models.Designation", "Designation")
                        .WithMany("Employees")
                        .HasForeignKey("DesignationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_employee_designation");

                    b.HasOne("Ergon.Models.LeaveEntitlement", "LeaveEntitlement")
                        .WithMany("Employees")
                        .HasForeignKey("LeaveEntitlementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_employee_leaveentitlement");

                    b.HasOne("Ergon.Models.Employee", "Manager")
                        .WithMany("Subordinates")
                        .HasForeignKey("ReportsTo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_employee_employee");

                    b.HasOne("Ergon.Models.Role", "Role")
                        .WithMany("Employees")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_employee_role");

                    b.HasOne("Ergon.Models.SalaryStructure", "SalaryStructure")
                        .WithMany("Employees")
                        .HasForeignKey("SalaryStructureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_employee_salarystructure");

                    b.HasOne("Ergon.Models.Shift", "Shift")
                        .WithMany("Employees")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_employee_shift");

                    b.HasOne("Ergon.Models.State", "State")
                        .WithMany("Employees")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("City");

                    b.Navigation("Country");

                    b.Navigation("Department");

                    b.Navigation("Designation");

                    b.Navigation("LeaveEntitlement");

                    b.Navigation("Manager");

                    b.Navigation("Role");

                    b.Navigation("SalaryStructure");

                    b.Navigation("Shift");

                    b.Navigation("State");
                });

            modelBuilder.Entity("Ergon.Models.EmployeeDocument", b =>
                {
                    b.HasOne("Ergon.Models.Employee", "Employee")
                        .WithMany("EmployeeDocuments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_employeedocument_employee");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Ergon.Models.Leave", b =>
                {
                    b.HasOne("Ergon.Models.Employee", "ActionedByEmployee")
                        .WithMany("ActionedLeaves")
                        .HasForeignKey("ActionedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_leave_actionedby_employee");

                    b.HasOne("Ergon.Models.Employee", "Employee")
                        .WithMany("Leaves")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_leave_employee");

                    b.HasOne("Ergon.Models.LeaveType", "LeaveType")
                        .WithMany("Leaves")
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_leave_leavetype");

                    b.Navigation("ActionedByEmployee");

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("Ergon.Models.LeaveEntitlementComponent", b =>
                {
                    b.HasOne("Ergon.Models.LeaveEntitlement", "LeaveEntitlement")
                        .WithMany("LeaveEntitlementComponents")
                        .HasForeignKey("LeaveEntitlementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_leaveentitlementcomponent_leaveentitlement");

                    b.HasOne("Ergon.Models.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_leaveentitlementcomponent_leavetype");

                    b.Navigation("LeaveEntitlement");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("Ergon.Models.Notification", b =>
                {
                    b.HasOne("Ergon.Models.Employee", "Employee")
                        .WithMany("Notifications")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_notification_employee");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Ergon.Models.Payroll", b =>
                {
                    b.HasOne("Ergon.Models.Employee", "ApprovedByEmployee")
                        .WithMany("ApprovedPayrolls")
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_payroll_approvedby_employee");

                    b.HasOne("Ergon.Models.Employee", "Employee")
                        .WithMany("Payrolls")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payroll_employee");

                    b.Navigation("ApprovedByEmployee");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Ergon.Models.PayrollComponent", b =>
                {
                    b.HasOne("Ergon.Models.Payroll", "Payroll")
                        .WithMany("PayrollComponents")
                        .HasForeignKey("PayrollId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payrollcomponent_payroll");

                    b.Navigation("Payroll");
                });

            modelBuilder.Entity("Ergon.Models.RefreshToken", b =>
                {
                    b.HasOne("Ergon.Models.Employee", "Employee")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_refreshtoken_employee");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Ergon.Models.ReviewCycleDetails", b =>
                {
                    b.HasOne("Ergon.Models.Employee", "Employee")
                        .WithMany("ReviewCycleDetails")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reviewcycledetails_employee");

                    b.HasOne("Ergon.Models.ReviewCycle", "ReviewCycle")
                        .WithMany("ReviewCycleDetails")
                        .HasForeignKey("ReviewCycleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reviewcycledetails_reviewcycle");

                    b.Navigation("Employee");

                    b.Navigation("ReviewCycle");
                });

            modelBuilder.Entity("Ergon.Models.SalaryComponent", b =>
                {
                    b.HasOne("Ergon.Models.SalaryStructure", "SalaryStructure")
                        .WithMany("SalaryComponents")
                        .HasForeignKey("SalaryStructureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_salarycomponent_salarystructure");

                    b.Navigation("SalaryStructure");
                });

            modelBuilder.Entity("Ergon.Models.Branch", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Ergon.Models.City", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Ergon.Models.Country", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Ergon.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Ergon.Models.Designation", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Ergon.Models.Employee", b =>
                {
                    b.Navigation("ActionedLeaves");

                    b.Navigation("ApprovedPayrolls");

                    b.Navigation("Attendances");

                    b.Navigation("BankAccounts");

                    b.Navigation("EmployeeDocuments");

                    b.Navigation("Leaves");

                    b.Navigation("Notifications");

                    b.Navigation("Payrolls");

                    b.Navigation("RefreshTokens");

                    b.Navigation("ReviewCycleDetails");

                    b.Navigation("Subordinates");
                });

            modelBuilder.Entity("Ergon.Models.LeaveEntitlement", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("LeaveEntitlementComponents");
                });

            modelBuilder.Entity("Ergon.Models.LeaveType", b =>
                {
                    b.Navigation("Leaves");
                });

            modelBuilder.Entity("Ergon.Models.Payroll", b =>
                {
                    b.Navigation("PayrollComponents");
                });

            modelBuilder.Entity("Ergon.Models.ReviewCycle", b =>
                {
                    b.Navigation("ReviewCycleDetails");
                });

            modelBuilder.Entity("Ergon.Models.Role", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Ergon.Models.SalaryStructure", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("SalaryComponents");
                });

            modelBuilder.Entity("Ergon.Models.Shift", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Ergon.Models.State", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
